language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run src/
  - vendor/bin/phpunit -c phpunit.xml.dist
